repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9 # Ruff version
    hooks:
      - id: ruff # Run the linter.
        name: Run Linter Check (Ruff)
        args: [ --fix, --unsafe-fixes ]
        files: ^(instructor|tests|examples)/
      - id: ruff-format       # Run the formatter.
        name: Run Formatter (Ruff)

  - repo: local
    hooks:
      - id: uv-lock-check
        name: Check uv.lock is up-to-date
        entry: uv
        args: [lock, --check]
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false
        
      - id: uv-lock-validate
        name: Validate dependency resolution
        entry: bash
        args: ["-c", "uv lock --check && echo 'Dependencies can be resolved correctly'"]
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false
