authors:
  jxnl:
    name: Jason Liu
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4852235?v=4
    url: https://twitter.com/intent/follow?screen_name=jxnlco
  ivanleomk:
    name: Ivan Leo
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1838778744468836353/utYfioiO_400x400.jpg
    url: https://twitter.com/intent/follow?screen_name=ivanleomk
  anmol:
    name: Anmol Jawandha
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1248544843556466693/PgxUIeBs_400x400.jpg
  joschkabraun:
    name: Joschka Braun
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1601251353531224065/PYpqKsjL_400x400.jpg
    url: https://twitter.com/joschkabraun
  sarahchieng:
    name: Sarah Chieng
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1755455116595834880/Hxh5ceRZ_400x400.jpg
    url: https://twitter.com/sarahchieng
  zilto:
    name: Thierry Jean
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/68975210?v=4
    url: https://www.linkedin.com/in/thierry-jean/
  yanomaly:
    name: Yan
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/87994542?v=4
